#!/usr/bin/env bash
# a Bash script that will display information about subdomains

subdomain_info() {
	answer_section=$(dig $1 | grep -A1 'ANSWER SECTION' | tail -n 1)
	subdomain=$(echo "$answer_section" | awk '{print $1;}' FS=.)
	record_type=$(echo "$answer_section" | awk '{print $4;}')
	ip=$(echo "$answer_section" | awk '{print $5}')

	echo "The subdomain $subdomain is a $record_type record and points to $ip"
}

if [ $# -eq 1 ]
then
	subdomain_info "www.$1" 
	subdomain_info "lb-01.$1"
	subdomain_info "web-01.$1"
	subdomain_info "web-02.$1"
elif [ $# -eq 2 ]
then
	subdomain_info "$2.$1"
fi
