#!/usr/bin/env bash
#  a Bash script that configures a new Ubuntu machine to:
#	Install nginx on your server
#	Nginx should be listening on port 80
#	When querying Nginx at its root / with a GET request using curl,
#	it must return a page that contains the string Hello World!

apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
