#!/usr/bin/env bash
# a bash script that configures an nginx server

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/0xnuru permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Configure Nginx so that its HTTP response contains a custom header
new_string="\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "s/listen \[\:\:\]:80 default_server;/listen [::]:80 default_server;\n\n$new_string/" /etc/nginx/sites-enabled/default

# restart nginx after implementing changes
sudo service nginx restart
