#!/usr/bin/env bash
#first advanced task


echo "$$" > /var/run/myscript.pid

cleanup() {
	rm /var/run/myscript.pid
	exit
}


while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && termfunc' SIGTERM
	trap 'cleanup' SIGQUIT
done
