#!/usr/bin/env bash
# fizzbuzz but in bash

i=1

for ((; i < 101; i++))
{
    if [[ $(( i % 3 )) -eq 0 && $((i % 5)) -eq 0 ]]
    then
        echo "FizzBuzz"
    elif [ $((i%3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((i%5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
}
